<?php
$mysql_host='localhost';
$mysql_login='root';
$mysql_pass='root';
$mysql_db='catchchallenger';
$base_datapack_explorer_site_path='/official-server/datapack-explorer/';
$base_datapack_site_path='/datapack/';
$datapack_path='../datapack/';
//$map_generator='/home/user/CatchChallenger/tools/build-map2pngGUI-Qt5-Debug/map2pngGUI';
